export type AppCategory =
  | "social_media"
  | "entertainment"
  | "communication"
  | "productivity"
  | "utilities"
  | "education"
  | "health"
  | "finance"
  | "shopping"
  | "gaming"
  | "news"
  | "travel"
  | "food"
  | "music"
  | "other";

const PACKAGE_CATEGORY_MAP: Record<string, AppCategory> = {
  "com.instagram.android": "social_media",
  "com.facebook.katana": "social_media",
  "com.facebook.lite": "social_media",
  "com.facebook.orca": "social_media",
  "com.twitter.android": "social_media",
  "com.zhiliaoapp.musically": "social_media",
  "com.linkedin.android": "social_media",
  "com.pinterest": "social_media",
  "com.snapchat.android": "social_media",
  "com.reddit.frontpage": "social_media",
  "com.ss.android.ugc.trill": "social_media",

  "com.google.android.youtube": "entertainment",
  "com.tiktok": "entertainment",
  "com.google.android.apps.youtube.kids": "entertainment",
  "com.netflix.mediaclient": "entertainment",
  "com.disney.disneyplus": "entertainment",
  "com.amazon.avod.thirdpartyclient": "entertainment",
  "com.viu": "entertainment",
  "com.vidio.android": "entertainment",
  "com.wetv.intl": "entertainment",
  "com.tencent.ig": "gaming",
  "com.mobile.legends": "gaming",
  "com.supercell.magic": "gaming",
  "com.dts.freefireth": "gaming",
  "com.mojang.minecraftpe": "gaming",
  "com.roblox.client": "gaming",

  "com.whatsapp": "communication",
  "org.telegram.messenger": "communication",
  "com.Slack": "communication",
  "com.discord": "communication",
  "com.viber.voip": "communication",
  "com.linecorp.lineline": "communication",
  "jp.naver.line.android": "communication",
  "com.google.android.apps.messaging": "communication",
  "com.google.android.dialer": "communication",
  "com.truecaller": "communication",
  "com.skype.raider": "communication",
  "com.zoom.us": "communication",
  "com.microsoft.teams": "communication",

  "com.spotify.music": "music",
  "com.google.android.apps.youtube.music": "music",
  "com.amazon.mp3": "music",
  "com.soundcloud.android": "music",
  "id.co.joox": "music",
  "com.rhapsody": "music",

  "com.gojek.app": "utilities",
  "id.dana": "utilities",
  "com.ovo.android": "utilities",
  "com.shopee.package": "shopping",
  "com.shopee.id": "shopping",
  "id.bukalapak.android": "shopping",
  "com.tokopedia.tkpd": "shopping",
  "com.lazada.android": "shopping",
  "com.blibli.android": "shopping",
  "id.zettapro.app": "shopping",

  "com.google.android.apps.docs": "productivity",
  "com.google.android.apps.docs.editors.docs": "productivity",
  "com.google.android.apps.docs.editors.sheets": "productivity",
  "com.google.android.apps.docs.editors.slides": "productivity",
  "com.microsoft.office.outlook": "productivity",
  "com.microsoft.office.word": "productivity",
  "com.microsoft.office.excel": "productivity",
  "com.microsoft.office.powerpoint": "productivity",
  "com.notion.id": "productivity",
  "notion.id": "productivity",
  "com.todoist": "productivity",
  "com.evernote": "productivity",
  "com.google.android.keep": "productivity",
  "com.apple.mobileslideshow": "productivity",
  "com.google.android.apps.tasks": "productivity",
  "com.trello": "productivity",
  "cc.forestapp": "productivity",
  "com.google.android.calendar": "productivity",
  "com.microsoft.todos": "productivity",

  "com.grammarly.production": "education",
  "com.duolingo": "education",
  "org.khanacademy.android": "education",
  "com.coursera.android": "education",
  "com.udemy.android": "education",
  "com.quora.android": "education",
  "com.brainly": "education",
  "com.ruangguru.live": "education",
  "com.quipper.video": "education",
  "com.zenius.app": "education",
  "id.co.schoolmedia.chemistry": "education",

  "com.google.android.apps.fitness": "health",
  "com.fitbit.FitbitMobile": "health",
  "com.strava": "health",
  "com.myfitnesspal.android": "health",
  "com.nike.ntc": "health",
  "com.keep.android": "health",
  "com.headspace": "health",
  "com.calm.android": "health",

  "com.financial.calculator": "finance",
  "com.intuit.turbotax": "finance",
  "com.paypal.android.p2pmobile": "finance",
  "com.venmo": "finance",
  "com.westernunion.mobile": "finance",
  "com.bca.mobile": "finance",
  "com.bri.brimo": "finance",
  "com.bni": "finance",
  "com.mandiri": "finance",
  "com.bankbsi.mobile": "finance",
  "com.sepulsa.android": "finance",
  "com.flip.id": "finance",

  "com.google.android.apps.magazines": "news",
  "com.bbc.mobile.news": "news",
  "com.cnn.mobile.android.phone": "news",
  "com.nytimes.android": "news",
  "id.co.kumparan": "news",
  "com.detik.android": "news",
  "id.co.bbcmedia": "news",
  "com.templatematerial.liputan6": "news",
  "id.co.cnn.mobile": "news",
  "com.sindonews.android": "news",

  "com.google.android.apps.maps": "travel",
  "com.grabtaxi.passenger": "travel",
  "com.grab.food": "food",
  "com.gojek.food": "food",
  "com.mcdonalds.app": "food",
  "com.starbucks.id": "food",
  "id.gofood": "food",
  "com.ubercab": "travel",
  "com.airbnb.android": "travel",
  "com.booking": "travel",
  "com.traveloka.android": "travel",
  "com.tiket.tix": "travel",
  "com.agoda.mobile": "travel",

  "com.android.chrome": "utilities",
  "org.mozilla.firefox": "utilities",
  "com.brave.browser": "utilities",
  "com.opera.browser": "utilities",
  "com.sec.android.app.sbrowser": "utilities",
  "com.google.android.apps.photos": "utilities",
  "com.google.android.apps.nbu.files": "utilities",
  "com.android.vending": "utilities",
  "com.google.android.apps.walletnfcrel": "finance",
  "com.android.settings": "utilities",
  "com.android.systemui": "utilities",
  "com.google.android.googlequicksearchbox": "utilities",
  "com.samsung.android.messaging": "communication",
  "com.samsung.android.calendar": "productivity",
  "com.samsung.android.app.notes": "productivity",
};

const PACKAGE_APP_NAMES: Record<string, string> = {
  "com.instagram.android": "Instagram",
  "com.facebook.katana": "Facebook",
  "com.facebook.lite": "Facebook Lite",
  "com.facebook.orca": "Messenger",
  "com.twitter.android": "X (Twitter)",
  "com.zhiliaoapp.musically": "TikTok",
  "com.linkedin.android": "LinkedIn",
  "com.pinterest": "Pinterest",
  "com.snapchat.android": "Snapchat",
  "com.reddit.frontpage": "Reddit",
  "com.google.android.youtube": "YouTube",
  "com.tiktok": "TikTok",
  "com.netflix.mediaclient": "Netflix",
  "com.whatsapp": "WhatsApp",
  "org.telegram.messenger": "Telegram",
  "com.Slack": "Slack",
  "com.discord": "Discord",
  "com.linecorp.lineline": "LINE",
  "com.spotify.music": "Spotify",
  "com.google.android.apps.youtube.music": "YouTube Music",
  "com.gojek.app": "Gojek",
  "id.dana": "DANA",
  "com.ovo.android": "OVO",
  "com.shopee.id": "Shopee",
  "id.bukalapak.android": "Bukalapak",
  "com.tokopedia.tkpd": "Tokopedia",
  "com.lazada.android": "Lazada",
  "com.grabtaxi.passenger": "Grab",
  "com.traveloka.android": "Traveloka",
  "com.google.android.gm": "Gmail",
  "com.google.android.apps.maps": "Google Maps",
  "com.android.chrome": "Chrome",
  "com.google.android.apps.docs": "Google Docs",
  "com.notion.id": "Notion",
  "com.todoist": "Todoist",
  "com.duolingo": "Duolingo",
  "com.ruangguru.live": "Ruangguru",
  "com.strava": "Strava",
  "com.bca.mobile": "BCA Mobile",
  "com.bri.brimo": "BRImo",
  "com.detik.android": "Detik",
  "id.co.kumparan": "Kumparan",
  "com.tencent.ig": "PUBG Mobile",
  "com.mobile.legends": "Mobile Legends",
  "com.dts.freefireth": "Free Fire",
  "com.mojang.minecraftpe": "Minecraft",
  "com.roblox.client": "Roblox",
  "com.viu": "Viu",
  "com.vidio.android": "Vidio",
  "id.co.joox": "JOOX",
};

export function getAppCategory(packageName: string): AppCategory {
  return PACKAGE_CATEGORY_MAP[packageName] ?? "other";
}

export function getAppName(packageName: string): string {
  return PACKAGE_APP_NAMES[packageName] ?? packageName;
}
